All tasks of the ex15_js-oop are ready
kanstudio/external-courses pull request #24
Opened 2018-11-27 11:33 UTC by kanstudio

2018-11-27 17:30 UTC, DairoGrey requested changes

2018-11-27 17:30 UTC, DairoGrey commented on src/ex15_js-oop/task-02.js
> +    Object.defineProperty(room, 'consumption', {
Надо бы в конструктор **Room** перенести

2018-11-28 09:24 UTC, kanstudio commented on src/ex15_js-oop/task-02.js
> +    Object.defineProperty(room, 'consumption', {
Готово

2018-11-28 14:48 UTC, DairoGrey approved these changes

2018-11-28 14:48 UTC, merged