ex16_library is ready
kanstudio/external-courses pull request #25
Opened 2018-12-11 18:14 UTC by kanstudio

2018-12-14 13:42 UTC, DairoGrey requested changes

2018-12-14 13:42 UTC, DairoGrey commented on src/ex16_library/index.js
> +    const filetypes = /jpeg|jpg|png|gif/;
Для определения типов по расширению можно воспользоваться пакетом [mime](https://www.npmjs.com/package/mime)

2018-12-14 13:42 UTC, DairoGrey commented on src/ex16_library/index.js
> +                keywords = keywords.replace(/\s+/g, ' ');
Тут лучше не присваивать промежуточный результат переменным, а зачейнить вызовы.

2018-12-14 13:42 UTC, DairoGrey commented on src/ex16_library/public/js/Model.js
> +            id: data.id ? data.id : this._book.server.id,
```javascript
data.id ? data.id : this._book.server.id
```
тоже самое, что и
```javascript
data.id || this._book.server.id
```

2018-12-14 13:42 UTC, DairoGrey commented on src/ex16_library/public/js/infra/calc.js
> +        for (let i = 0; i < arr.length; i++) {
_arr_.**reduce**?

2018-12-14 19:13 UTC, kanstudio commented on src/ex16_library/public/js/infra/calc.js
> +        for (let i = 0; i < arr.length; i++) {
Я умышленно не стал делать через reduce:
```
return arr.reduce((sum, item) => {
    if (typeof item !== 'number' || isNaN(item)) return NaN;
    return sum += item;
}, 0) / arr.length;
```
Потому что мне нужно прервать цикл, если хотя бы один элемент массива не число. А в методах по обходу массивов прервать цикл нельзя (break не работает), а return не прервёт главную функцию, а просто вернёт значение коллбека текущей итерации.

Через reduce тоже работало бы правильно, но такое решение стоило бы больших вычислительных ресурсов. Если передавать в функцию очень большие массивы, у которых среди первых элементов будет невалидный, то разница в скорости будет очень ощутима.
---
Заменил в проверке элементов на number ноль на NaN. Так логичнее, думаю.

2018-12-14 19:17 UTC, kanstudio commented on src/ex16_library/public/js/Model.js
> +            id: data.id ? data.id : this._book.server.id,
Переделал

2018-12-14 19:17 UTC, kanstudio commented on src/ex16_library/index.js
> +                keywords = keywords.replace(/\s+/g, ' ');
Понял, переделал

2018-12-14 19:17 UTC, kanstudio commented on src/ex16_library/index.js
> +    const filetypes = /jpeg|jpg|png|gif/;
Использовал mime

2018-12-18 08:57 UTC, DairoGrey requested changes

2018-12-18 08:57 UTC, DairoGrey commented on src/ex16_library/public/js/infra/calc.js
> +        for (let i = 0; i < arr.length; i++) {
Это можно решить комбинацией _arr_.**every** и _arr_.**reduce**. А по поводу больших массивов данных могу сказать только одно: преждевременные оптимизации - зло.

2018-12-18 08:57 UTC, DairoGrey commented on src/ex16_library/index.js
> +app.post('/api/books', (req, res, next) => {
Эти два middleware лучше вынести в отдельный файл и сделать общую функцию для обработки полей (они очень похожи, можно выделить общее "ядро", но оставить два middleware).

2018-12-18 14:31 UTC, kanstudio commented on src/ex16_library/public/js/infra/calc.js
> +        for (let i = 0; i < arr.length; i++) {
Переделал.
Вообще, Дональд Кнут имел в виду преждевременную оптимизацию в ущерб читаемости и поддерживаемости кода. Но если изначально писать эффективный и хорошо читаемый код, то будет ли он считаться оптимизированным преждевременно?)

2018-12-18 14:31 UTC, kanstudio commented on src/ex16_library/index.js
> +app.post('/api/books', (req, res, next) => {
Переделал.

2018-12-20 10:14 UTC, DairoGrey approved these changes

2018-12-20 10:14 UTC, merged